// SPDX-License-Identifier: MIT
// Copyright (c) 2026 bvasilenko
import { mkdir, writeFile, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { Command } from 'commander';
import chalk from 'chalk';

type Forge = 'github' | 'gitlab' | 'both';

export interface InitCiOptions {
  forge: Forge;
  registry: 'ghcr' | 'gitlab' | 'dockerhub';
  imageName?: string;
  runtime: 'nginx' | 'bun';
  deployKind: 'compose-ssh' | 'coolify' | 'none';
  printSecrets?: boolean;
  ghCli?: boolean;
  glabCli?: boolean;
  force?: boolean;
  cwd?: string;
}

export interface InitCiResult {
  written: string[];
  skipped: string[];
  secretsToSet: { name: string; description: string }[];
}

interface FileSpec {
  path: string;
  content: string;
  overwrite: boolean;
}

const DEFAULT_OPTIONS: InitCiOptions = {
  forge: 'both',
  registry: 'ghcr',
  imageName: undefined,
  runtime: 'nginx',
  deployKind: 'compose-ssh',
  printSecrets: false,
  ghCli: false,
  glabCli: false,
  force: false,
};

function renderManifest(opts: InitCiOptions, repoSlug: string): string {
  const image = opts.imageName ?? repoSlug;
  return JSON.stringify(
    {
      $schema: 'https://booga.dev/vbrand/deploy.schema.json',
      vbrandCi: '0.3.0',
      registry: {
        kind: opts.registry,
        imageName: image,
        additionalTags: ['latest'],
      },
      deploy: {
        kind: opts.deployKind,
        webhookSecret: opts.deployKind === 'coolify' ? 'COOLIFY_WEBHOOK' : null,
        tokenSecret: opts.deployKind === 'coolify' ? 'COOLIFY_TOKEN' : null,
        sshSecret: opts.deployKind === 'compose-ssh' ? 'DEPLOY_SSH_KEY' : null,
        host: opts.deployKind === 'compose-ssh' ? 'ssh://deploy@example.com' : null,
      },
      build: {
        runtime: opts.runtime,
        context: '.',
        platforms: ['linux/amd64'],
      },
    },
    null,
    2,
  );
}

const DOCKERFILE_TEMPLATE = `# syntax=docker/dockerfile:1.7
# Generated by vbrand 0.3.0 init-ci. User-owned after first emission.
ARG RUNTIME=nginx
ARG BUN_VERSION=1.2
ARG NGINX_VERSION=1.27-alpine

FROM oven/bun:\${BUN_VERSION} AS deps
WORKDIR /app
COPY package.json bun.lock* package-lock.json* ./
RUN bun install --frozen-lockfile || bun install

FROM oven/bun:\${BUN_VERSION} AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

FROM nginx:\${NGINX_VERSION} AS runtime-nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=10s --timeout=2s CMD wget -q -O- http://localhost/ >/dev/null || exit 1

FROM oven/bun:\${BUN_VERSION}-slim AS runtime-bun
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./
EXPOSE 3000
HEALTHCHECK --interval=10s --timeout=2s CMD wget -q -O- http://localhost:3000/ >/dev/null || exit 1
CMD ["bun", "run", "dist/server.js"]

FROM runtime-\${RUNTIME} AS final
`;

const DOCKERIGNORE_TEMPLATE = `node_modules
dist
.git
.github
.vbrand
vbrand/.cache
vbrand/.deploy
*.log
.env
.env.*
!.env.example
coverage
.DS_Store
`;

function renderGithubWorkflow(opts: InitCiOptions): string {
  const ghcrLogin = opts.registry === 'ghcr';
  return `# Generated by vbrand 0.3.0. Do not edit unless you accept ownership.
# Re-sync with \`npx @booga/vbrand sync-ci\` (planned for 0.3.1).
name: vbrand-deploy

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to build and deploy (default: git short sha)'
        required: false

concurrency:
  group: vbrand-deploy-\${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # vbrand-preserve
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Read deploy manifest
        id: cfg
        run: |
          echo "registry=$(jq -r .registry.kind vbrand.deploy.json)"     >> "$GITHUB_OUTPUT"
          echo "image=$(jq -r .registry.imageName vbrand.deploy.json)"   >> "$GITHUB_OUTPUT"
          echo "runtime=$(jq -r .build.runtime vbrand.deploy.json)"      >> "$GITHUB_OUTPUT"
          echo "deploy=$(jq -r .deploy.kind vbrand.deploy.json)"         >> "$GITHUB_OUTPUT"

      - uses: oven-sh/setup-bun@v2
        with: { bun-version: '1.2.x' }

      - name: Build site
        run: |
          bun install --frozen-lockfile
          bun run build

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
${
  ghcrLogin
    ? `      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}`
    : `      - uses: docker/login-action@v3
        with:
          registry: \${{ steps.cfg.outputs.registry }}
          username: \${{ secrets.REGISTRY_USERNAME }}
          password: \${{ secrets.REGISTRY_TOKEN }}`
}

      - name: Compute tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${
            ghcrLogin
              ? `ghcr.io/\${{ steps.cfg.outputs.image }}`
              : `\${{ steps.cfg.outputs.image }}`
          }
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha,prefix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            RUNTIME=\${{ steps.cfg.outputs.runtime }}
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Trigger deploy
        if: steps.cfg.outputs.deploy == 'coolify'
        env:
          WEBHOOK: \${{ secrets.COOLIFY_WEBHOOK }}
          TOKEN: \${{ secrets.COOLIFY_TOKEN }}
          DIGEST: \${{ steps.push.outputs.digest }}
        run: |
          curl --fail-with-body -X POST "$WEBHOOK" \\
            -H "Authorization: Bearer $TOKEN" \\
            -H 'Content-Type: application/json' \\
            -d "{\\"image_digest\\":\\"$DIGEST\\",\\"force\\":true}"
`;
}

function renderGitlabCi(_opts: InitCiOptions): string {
  return `# Generated by vbrand 0.3.0. Do not edit unless you accept ownership.
# Re-sync with \`npx @booga/vbrand sync-ci\` (planned for 0.3.1).
stages:
  - build
  - deploy

variables:
  VBRAND_MANIFEST: vbrand.deploy.json

vbrand-build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
    - if: $CI_PIPELINE_SOURCE == "web"
  before_script:
    - apk add --no-cache jq curl
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export IMAGE=$(jq -r .registry.imageName $VBRAND_MANIFEST)
    - export RUNTIME=$(jq -r .build.runtime $VBRAND_MANIFEST)
    - docker buildx create --use --name vbrand-builder || true
    - docker buildx build --push --build-arg RUNTIME=$RUNTIME -t $CI_REGISTRY/$IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY/$IMAGE:latest .

vbrand-deploy:
  stage: deploy
  image: alpine:3
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
  before_script:
    - apk add --no-cache jq curl
  script:
    - export DEPLOY_KIND=$(jq -r .deploy.kind $VBRAND_MANIFEST)
    - |
      if [ "$DEPLOY_KIND" = "coolify" ]; then
        curl --fail-with-body -X POST "$COOLIFY_WEBHOOK" \\
          -H "Authorization: Bearer $COOLIFY_TOKEN" \\
          -H 'Content-Type: application/json' \\
          -d "{\\"image_tag\\":\\"$CI_COMMIT_TAG\\",\\"force\\":true}"
      else
        echo "deploy.kind=$DEPLOY_KIND - no in-CI deploy step; user runs 'vbrand deploy' locally"
      fi
`;
}

function renderSetSecretsScript(opts: InitCiOptions): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# SPDX-License-Identifier: MIT',
    '# Generated by vbrand 0.3.0 init-ci. Run this script ONCE to set secrets.',
    '# vbrand never sees secret values: this script reads them from your terminal',
    '# and pipes directly to your forge CLI. vbrand process is already exited.',
    'set -euo pipefail',
    '',
    'prompt() {',
    '  local name="$1"; local desc="$2"',
    '  printf "%s\\n  (%s)\\n  > " "$name" "$desc" >&2',
    '  read -rs val',
    '  printf "\\n" >&2',
    '  printf "%s" "$val"',
    '}',
    '',
  ];

  const ghLines: string[] = [];
  const glLines: string[] = [];

  if (opts.deployKind === 'compose-ssh') {
    ghLines.push('prompt DEPLOY_SSH_KEY "private SSH key (ed25519 recommended) for the deploy user" | gh secret set DEPLOY_SSH_KEY --body -');
    glLines.push('prompt DEPLOY_SSH_KEY "private SSH key (ed25519 recommended) for the deploy user" | glab variable create DEPLOY_SSH_KEY --value-from-stdin');
  }
  if (opts.deployKind === 'coolify') {
    ghLines.push('prompt COOLIFY_WEBHOOK "Coolify webhook URL (deploy trigger)" | gh secret set COOLIFY_WEBHOOK --body -');
    ghLines.push('prompt COOLIFY_TOKEN "Coolify API bearer token (deploy permission)" | gh secret set COOLIFY_TOKEN --body -');
    glLines.push('prompt COOLIFY_WEBHOOK "Coolify webhook URL" | glab variable create COOLIFY_WEBHOOK --value-from-stdin');
    glLines.push('prompt COOLIFY_TOKEN "Coolify API bearer token" | glab variable create COOLIFY_TOKEN --value-from-stdin');
  }
  if (opts.registry === 'dockerhub') {
    ghLines.push('prompt REGISTRY_USERNAME "Docker Hub username" | gh secret set REGISTRY_USERNAME --body -');
    ghLines.push('prompt REGISTRY_TOKEN "Docker Hub access token (write:packages scope)" | gh secret set REGISTRY_TOKEN --body -');
  }

  if (opts.forge === 'github' || opts.forge === 'both') {
    lines.push('# --- GitHub secrets (uses `gh secret set`) ---');
    lines.push('if command -v gh >/dev/null 2>&1; then');
    for (const l of ghLines.length ? ghLines : ['echo "no secrets required for this manifest configuration"']) {
      lines.push('  ' + l);
    }
    lines.push('else');
    lines.push('  echo "gh CLI not found; install from https://cli.github.com or set secrets manually"');
    lines.push('fi');
    lines.push('');
  }
  if (opts.forge === 'gitlab' || opts.forge === 'both') {
    lines.push('# --- GitLab variables (uses `glab variable create`) ---');
    lines.push('if command -v glab >/dev/null 2>&1; then');
    for (const l of glLines.length ? glLines : ['echo "no variables required for this manifest configuration"']) {
      lines.push('  ' + l);
    }
    lines.push('else');
    lines.push('  echo "glab CLI not found; install from https://gitlab.com/gitlab-org/cli or set variables manually"');
    lines.push('fi');
    lines.push('');
  }
  lines.push('echo "Done. Verify in your forge UI."');
  return lines.join('\n') + '\n';
}

function collectSecretsToSet(opts: InitCiOptions): { name: string; description: string }[] {
  const secrets: { name: string; description: string }[] = [];
  if (opts.deployKind === 'compose-ssh') {
    secrets.push({
      name: 'DEPLOY_SSH_KEY',
      description: 'private SSH key (ed25519 recommended) for the deploy user',
    });
  }
  if (opts.deployKind === 'coolify') {
    secrets.push({
      name: 'COOLIFY_WEBHOOK',
      description: 'Coolify webhook URL (deploy trigger)',
    });
    secrets.push({
      name: 'COOLIFY_TOKEN',
      description: 'Coolify API bearer token (deploy permission)',
    });
  }
  if (opts.registry === 'dockerhub') {
    secrets.push({
      name: 'REGISTRY_USERNAME',
      description: 'Docker Hub username',
    });
    secrets.push({
      name: 'REGISTRY_TOKEN',
      description: 'Docker Hub access token with write:packages scope',
    });
  }
  return secrets;
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function writeIfAllowed(spec: FileSpec, force: boolean): Promise<'written' | 'skipped'> {
  const dir = dirname(spec.path);
  await mkdir(dir, { recursive: true });
  if (!spec.overwrite && (await exists(spec.path)) && !force) {
    return 'skipped';
  }
  await writeFile(spec.path, spec.content, 'utf-8');
  return 'written';
}

export async function runInitCi(rawOpts: Partial<InitCiOptions> = {}): Promise<InitCiResult> {
  const opts: InitCiOptions = { ...DEFAULT_OPTIONS, ...rawOpts };
  const cwd = opts.cwd ?? process.cwd();
  const repoSlug = (rawOpts.imageName ?? 'owner/site').toString();

  const specs: FileSpec[] = [];

  if (opts.forge === 'github' || opts.forge === 'both') {
    specs.push({
      path: join(cwd, '.github', 'workflows', 'vbrand-deploy.yml'),
      content: renderGithubWorkflow(opts),
      overwrite: false,
    });
  }
  if (opts.forge === 'gitlab' || opts.forge === 'both') {
    specs.push({
      path: join(cwd, '.gitlab-ci.yml'),
      content: renderGitlabCi(opts),
      overwrite: false,
    });
  }
  specs.push({
    path: join(cwd, 'Dockerfile'),
    content: DOCKERFILE_TEMPLATE,
    overwrite: false,
  });
  specs.push({
    path: join(cwd, '.dockerignore'),
    content: DOCKERIGNORE_TEMPLATE,
    overwrite: true,
  });
  specs.push({
    path: join(cwd, 'vbrand.deploy.json'),
    content: renderManifest(opts, repoSlug),
    overwrite: false,
  });
  specs.push({
    path: join(cwd, 'scripts', 'vbrand-set-secrets.sh'),
    content: renderSetSecretsScript(opts),
    overwrite: true,
  });

  const written: string[] = [];
  const skipped: string[] = [];
  for (const spec of specs) {
    const result = await writeIfAllowed(spec, opts.force ?? false);
    if (result === 'written') written.push(spec.path);
    else skipped.push(spec.path);
  }

  return {
    written,
    skipped,
    secretsToSet: collectSecretsToSet(opts),
  };
}

export function buildInitCiCommand(): Command {
  const cmd = new Command('init-ci').description(
    'emit CI/CD scaffolding: workflow files + Dockerfile + deploy manifest + secret-setter script',
  );

  cmd
    .option('--forge <forge>', 'github | gitlab | both', 'both')
    .option('--registry <registry>', 'ghcr | gitlab | dockerhub', 'ghcr')
    .option('--image <name>', 'image name (owner/repo)')
    .option('--runtime <runtime>', 'nginx | bun', 'nginx')
    .option('--deploy <kind>', 'compose-ssh | coolify | none', 'compose-ssh')
    .option('--print-secrets', 'print secret list and exit (no files written)')
    .option('--force', 'overwrite existing files')
    .action(
      async (opts: {
        forge: Forge;
        registry: 'ghcr' | 'gitlab' | 'dockerhub';
        image?: string;
        runtime: 'nginx' | 'bun';
        deploy: 'compose-ssh' | 'coolify' | 'none';
        printSecrets?: boolean;
        force?: boolean;
      }) => {
        const runOpts: Partial<InitCiOptions> = {
          forge: opts.forge,
          registry: opts.registry,
          imageName: opts.image,
          runtime: opts.runtime,
          deployKind: opts.deploy,
          printSecrets: opts.printSecrets,
          force: opts.force,
        };

        if (opts.printSecrets) {
          const secrets = collectSecretsToSet({
            ...DEFAULT_OPTIONS,
            ...runOpts,
          });
          console.log(chalk.bold('Secrets your CI must have set:'));
          if (secrets.length === 0) {
            console.log(chalk.dim('  (none required for this manifest configuration)'));
          }
          for (const s of secrets) {
            console.log('  ' + chalk.cyan(s.name) + chalk.dim(' - ' + s.description));
          }
          console.log('');
          console.log(chalk.dim('GitHub: gh secret set NAME --body -'));
          console.log(chalk.dim('GitLab: glab variable create NAME --value-from-stdin'));
          return;
        }

        try {
          const result = await runInitCi(runOpts);
          console.log(chalk.green('Wrote:'));
          for (const p of result.written) console.log(chalk.dim('  + ' + p));
          if (result.skipped.length > 0) {
            console.log(chalk.yellow('Skipped (use --force to overwrite):'));
            for (const p of result.skipped) console.log(chalk.dim('  · ' + p));
          }
          console.log('');
          console.log(chalk.bold('Next step:'));
          console.log('  ' + chalk.cyan('bash scripts/vbrand-set-secrets.sh'));
          console.log(chalk.dim('  (vbrand process exits before this runs; your tokens never touch vbrand)'));
        } catch (err) {
          console.error(chalk.red(err instanceof Error ? err.message : String(err)));
          process.exit(1);
        }
      },
    );

  return cmd;
}
