// SPDX-License-Identifier: MIT
// Copyright (c) 2026 bvasilenko
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ensureDir } from '../fs.js';
import { VbrandType } from '../../schema.js';

interface NpmPackageJson {
  name: string;
  version: string;
  description: string;
  type: 'module';
  main: string;
  files: string[];
  keywords: string[];
  license: string;
  publishConfig: { access: 'public' };
}

export function buildNpmPackageJson(schema: VbrandType, version: string): NpmPackageJson {
  const id = schema.name.toLowerCase().replace(/\s+/g, '-');
  return {
    name: `@booga/brand-${id}`,
    version,
    description: schema.voice.repoDescription,
    type: 'module',
    main: 'index.js',
    files: ['*.json', '*.css', '*.md', 'assets/'],
    keywords: ['brand', 'vbrand', id],
    license: 'MIT',
    publishConfig: { access: 'public' },
  };
}

function buildReadme(schema: VbrandType): string {
  return [
    `# ${schema.name}`,
    '',
    schema.voice.repoDescription,
    '',
    '## Install',
    '',
    '```sh',
    `npx shadcn add brand:${schema.name.toLowerCase().replace(/\s+/g, '-')}`,
    '```',
    '',
    '## Tokens',
    '',
    `Primary: \`${schema.tokens.color['primary'] ?? 'unset'}\``,
    '',
    '---',
    '',
    '_Generated by [@booga/vbrand](https://github.com/bvasilenko)_',
    '',
  ].join('\n');
}

function buildIndexJs(): string {
  return [
    '// Re-export brand schema for programmatic consumers.',
    "import schema from './vbrand.schema.json' assert { type: 'json' };",
    'export default schema;',
    '',
  ].join('\n');
}

export function writeNpmShape(schema: VbrandType, version: string, distDir: string): string[] {
  const outDir = join(distDir, 'npm');
  ensureDir(outDir);

  const pkgPath = join(outDir, 'package.json');
  const readmePath = join(outDir, 'README.md');
  const indexPath = join(outDir, 'index.js');
  const licensePath = join(outDir, 'LICENSE');

  writeFileSync(
    pkgPath,
    JSON.stringify(buildNpmPackageJson(schema, version), null, 2) + '\n',
    'utf-8',
  );
  writeFileSync(readmePath, buildReadme(schema), 'utf-8');
  writeFileSync(indexPath, buildIndexJs(), 'utf-8');
  writeFileSync(
    licensePath,
    `MIT License\n\nCopyright (c) 2026 bvasilenko\n`,
    'utf-8',
  );

  return [pkgPath, readmePath, indexPath, licensePath];
}
