// SPDX-License-Identifier: MIT
// Copyright (c) 2026 bvasilenko
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ensureDir } from '../fs.js';
import { VbrandType, ThemeModeValues } from '../../schema.js';

function toVarName(key: string): string {
  return '--vb-' + key.replace(/[^a-zA-Z0-9-]/g, '-').replace(/-+/g, '-').toLowerCase();
}

function buildPrefixedVars(axisPrefix: string, tokens: Record<string, string>): string {
  return Object.keys(tokens)
    .sort()
    .map((key) => {
      const varName = axisPrefix ? toVarName(`${axisPrefix}-${key}`) : toVarName(key);
      return `  ${varName}: ${tokens[key]};`;
    })
    .join('\n');
}

function buildThemeBlock(mode: string, registry: Record<string, string>): string {
  const selector =
    mode === 'light'
      ? ':root, [data-theme="light"]'
      : `[data-theme="${mode}"]`;
  const vars = Object.keys(registry)
    .sort()
    .map((k) => `  ${toVarName(k)}: ${registry[k]};`)
    .join('\n');
  return `${selector} {\n${vars}\n}`;
}

const OPTIONAL_AXES: Array<{ prefix: string; key: keyof NonNullable<VbrandType['tokens']> }> = [
  { prefix: 'space', key: 'spacing' },
  { prefix: 'radius', key: 'radius' },
  { prefix: 'shadow', key: 'shadow' },
  { prefix: 'motion', key: 'motion' },
  { prefix: 'opacity', key: 'opacity' },
  { prefix: 'z', key: 'zIndex' },
];

export function emitCssVars(schema: VbrandType, outDir: string): string {
  ensureDir(outDir);

  const rootBlocks: string[] = [
    buildPrefixedVars('', schema.tokens.color),
    buildPrefixedVars('font', schema.tokens.type),
  ];

  for (const { prefix, key } of OPTIONAL_AXES) {
    const axis = schema.tokens[key];
    if (axis && Object.keys(axis).length > 0) {
      rootBlocks.push(buildPrefixedVars(prefix, axis));
    }
  }

  const lines: string[] = [
    '/* vbrand-tokens.css: generated by @booga/vbrand emit */',
    '',
    ':root {',
    rootBlocks.filter(Boolean).join('\n'),
    '}',
  ];

  if (schema.themes?.registry) {
    lines.push('');
    for (const mode of ThemeModeValues) {
      const registry = schema.themes.registry[mode];
      if (registry && Object.keys(registry).length > 0) {
        lines.push(buildThemeBlock(mode, registry));
        lines.push('');
      }
    }
  }

  const css = lines.join('\n').trimEnd() + '\n';
  const outPath = join(outDir, 'brand-tokens.css');
  writeFileSync(outPath, css, 'utf-8');
  return outPath;
}
